export { default as Sura, type ISura } from './Sura';
export { default as Translation, type ITranslation } from './Translation';
export { default as Interpretation, type IInterpretation } from './Interpretation';
export { default as AboutUs, type IAboutUs } from './AboutUs';
export { default as Author, type IAuthor } from './Author';
export { default as ContactUs, type IContactUs } from './ContactUs';
export { default as Help, type IHelp } from './Help';
export { default as User, type IUser } from './User';
export { default as AuditLog, type IAuditLog } from './AuditLog';
